name: ruby_3_4_3_bookworm

services:  
  ruby_pg:
    image: postgres:${PG_VERSION}
    container_name: ruby_pg
    restart: always
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  ruby_rails:
    build: .
    container_name: ruby_rails
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - ruby_pg
    links:
      - ruby_pg
    environment:
      - PG_HOST=${PG_HOST}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RAILS_PORT=${RAILS_PORT}
    volumes:
      - ./src:/home/app/src
      - ./data:/home/app/data