name: big_library

services:  
  big_library_db:
    image: postgres:${PG_VERSION}
    container_name: big_library_db
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  big_library_api:
    build: .
    container_name: big_library_api
    stdin_open: true
    tty: true      
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - big_library_db
    links:
      - big_library_db
    environment:
      - PG_HOST=${PG_HOST}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RAILS_PORT=${RAILS_PORT}
    volumes:
      - ./src:/home/app/src
      - ./data:/home/app/data
      - ./install:/home/app/install